apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: dev
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: testemail@gmail.com # add email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx